### Supermarket /products
GET http://localhost:1337/products


### Supermarket /categories
GET http://localhost:1337/categories


### Auth /register
POST http://localhost:1337/register
Content-Type: application/json

{
    "name" : "Bob Stevenson",
    "email" : "test@gmail.com",
    "password" : "thisispassword"
}


### Auth /login
POST http://localhost:1337/login
Content-Type: application/json

{
    "email" : "test@gmail.com",
    "password" : "thisispassword"
}


### House /createhouse
POST http://localhost:1337/createhouse
Authorization: Bearer <accessToken>
Content-Type: application/json

{
    "house_name" : "Cool Pals ONLY",
    "house_address" : "Rachelsmolen 1, 5612 MA Eindhoven"
}


### InHouse /testVerify
GET http://localhost:1337/testVerify
Authorization: Bearer <accessToken>


### InHouse /testNoVerify
GET http://localhost:1337/testNoVerify