GET http://localhost:3002/products


###
POST http://localhost:3002/register
Content-Type: application/json

{
    "name" : "Bob Stevenson",
    "email" : "test@gmail.com",
    "password" : "thisispassword"
}


###
POST http://localhost:3002/login
Content-Type: application/json

{
    "email" : "test@gmail.com",
    "password" : "thisispassword"
}


###
GET http://localhost:3002/test
Authorization: Bearer <accesToken>