apiVersion: v1
kind: Service
metadata:
    name: "hello-world"
    labels:
        app: "hello-world"
spec:
    type: LoadBalancer
    ports:
    - port: 1337
      targetPort: 1337
      protocol: TCP
      name: http
    selector:
        app: "hello-world"