pipeline {
    agent any
    stages {
        stage ("Docker") {
            steps {
                dockerfile {
                    dir Docker
                    filename 'Dockerfile'
                    label 'label-docker'
                }
            }
        }
    }
}